system_oceny/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using system_oceny.Models;

namespace system_oceny.Controllers
{
    public class CommentController : Controller
    {
        private FirmaDBCtxt db = new FirmaDBCtxt();
        //GET:
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Firmy/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "komentarzID, tresc, data, autor, FirmaId")] Komentarz komentarz)
        {
            komentarz.data = DateTime.Today;
            if (ModelState.IsValid)
            {
                db.Komentarze.Add(komentarz);
                db.SaveChanges();

                return RedirectToAction("Details", "Firmy", new { id = komentarz.FirmaId });
            }

            return View(komentarz);
        }

        // GET: /Comment/Edit/X
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Komentarz komentarz = db.Komentarze.Find(id);
            if (komentarz == null)
            {
                return HttpNotFound();
            }
            return View(komentarz);
        }

        // POST: /Comment/Edit/X
        [HttpPost]
        [Authorize]
        public ActionResult Edit([Bind(Include = "komentarzID, tresc, data, autor, FirmaId")] Komentarz komentarz)
        {
            // komentarz.data = DateTime.Today;
            if (ModelState.IsValid)
            {
                db.Entry(komentarz).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Firmy", new { id = komentarz.FirmaId });
            }
            return View(komentarz);
        }

        // GET: /Firmy/Delete/X
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Komentarz komentarz = db.Komentarze.Find(id);
            if (komentarz == null)
            {
                return HttpNotFound();
            }
            return View(komentarz);
        }

        // POST: /Firmy/Delete/X
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Komentarz komentarz = db.Komentarze.Find(id);
            db.Komentarze.Remove(komentarz);
            db.SaveChanges();
            return RedirectToAction("Details", "Firmy", new { id = komentarz.FirmaId });
        }
    }
}

system_oceny/Controllers/FirmyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using system_oceny.Models;

namespace system_oceny.Controllers
{
    public class FirmyController : Controller
    {
        private FirmaDBCtxt db = new FirmaDBCtxt();

        public ActionResult Index(string sortowanie, FirmaSzukaj Model)
        {
            ViewBag.SortedBy = sortowanie;
            ViewBag.SortByOcena = sortowanie == null ? "Ocena_Malejaco" : "";
            ViewBag.SortByNazwa = sortowanie == "Nazwa_Malejaco" ? "Nazwa_Rosnaco" : "Nazwa_Malejaco";
            ViewBag.SortByBranza = sortowanie == "Branza_Malejaco" ? "Branza_Rosnaco" : "Branza_Malejaco";
            ViewBag.SortByOcenaJ = sortowanie == "OcenaJ_Malejaco" ? "OcenaJ_Rosnaco" : "OcenaJ_Malejaco";
            ViewBag.SortByOcenaCz = sortowanie == "OcenaCz_Malejaco" ? "OcenaCz_Rosnaco" : "OcenaCz_Malejaco";
            ViewBag.SortByOcenaCe = sortowanie == "OcenaCe_Malejaco" ? "OcenaCe_Rosnaco" : "OcenaCe_Malejaco";
            var firmy = from i in db.Firmy
                        select i;

             //Wyszukiwanie
            if (ModelState.IsValid)
            {
                if (Model.MiastoZnajdz != null && Model.BranzaZnajdz != null && Model.NazwaZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.Nazwa.Contains(Model.NazwaZnajdz) && i.Branza.Contains(Model.BranzaZnajdz) && i.miasto.Contains(Model.MiastoZnajdz)
                            select i;
                }
                else if (Model.BranzaZnajdz != null && Model.NazwaZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.Nazwa.Contains(Model.NazwaZnajdz) && i.Branza.Contains(Model.BranzaZnajdz)
                            select i;
                }
                else if (Model.BranzaZnajdz != null && Model.MiastoZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.miasto.Contains(Model.MiastoZnajdz) && i.Branza.Contains(Model.BranzaZnajdz)
                            select i;
                }
                else if (Model.MiastoZnajdz != null && Model.NazwaZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.Nazwa.Contains(Model.NazwaZnajdz) && i.miasto.Contains(Model.MiastoZnajdz)
                            select i;
                }
                else if (Model.BranzaZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.Branza.Contains(Model.BranzaZnajdz)
                            select i;
                }
                else if (Model.NazwaZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.Nazwa.Contains(Model.NazwaZnajdz)
                            select i;
                }
                else if (Model.MiastoZnajdz != null)
                {
                    firmy = from i in db.Firmy
                            where i.miasto.Contains(Model.MiastoZnajdz)
                            select i;
                }
                ViewBag.BranzaZnajdz = Model.BranzaZnajdz;
                ViewBag.NazwaZnajdz = Model.NazwaZnajdz;
                ViewBag.MiastoZnajdz = Model.MiastoZnajdz;
            }


            //Sortowanie
            switch (sortowanie)
            {
                case "Nazwa_Malejaco":
                    firmy = firmy.OrderByDescending(s => s.Nazwa);
                    break;
                case "Nazwa_Rosnaco":
                    firmy = firmy.OrderBy(s => s.Nazwa);
                    break;
                case "Branza_Malejaco":
                    firmy = firmy.OrderByDescending(s => s.Branza);
                    break;
                case "Branza_Rosnaco":
                    firmy = firmy.OrderBy(s => s.Branza);
                    break;
                case "Ocena_Malejaco":
                    firmy = firmy.OrderBy(s => s.ocena);
                    break;
                case "OcenaJ_Malejaco":
                    firmy = firmy.OrderBy(s => s.ocena_j);
                    break;
                case "OcenaJ_Rosnaco":
                    firmy = firmy.OrderByDescending(s => s.ocena_j);
                    break;
                case "OcenaCe_Malejaco":
                    firmy = firmy.OrderBy(s => s.ocena_ce);
                    break;
                case "OcenaCe_Rosnaco":
                    firmy = firmy.OrderByDescending(s => s.ocena_ce);
                    break;
                case "OcenaCz_Malejaco":
                    firmy = firmy.OrderBy(s => s.ocena_cz);
                    break;
                case "OcenaCz_Rosnaco":
                    firmy = firmy.OrderByDescending(s => s.ocena_cz);
                    break;
                default:
                    firmy = firmy.OrderByDescending(s => s.ocena);
                    break;
            }
            return View(firmy.ToList());
        }

        // GET: /Firmy/Details/X
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firma firma = db.Firmy.Find(id);
            if (firma == null)
            {
                return HttpNotFound();
            }
            return View(firma);
        }

        // GET: /Firmy/Create
        [Authorize]
       public ActionResult Create()
        {
            return View();
        }

        // POST: /Firmy/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Branza,Nazwa,Opis,NIP, email, miasto, kod_pocztowy, adres,numer_telefonu")] Firma firma)
        {
            firma.ocena = 0;
            firma.ocena_cz = 0;
            firma.ocena_ce = 0;
            firma.ocena_j = 0;
            firma.ilosc_ocen = 0;
            if (ModelState.IsValid)
            {
                db.Firmy.Add(firma);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(firma);
        }

        // GET: /Firmy/Edit/X
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firma firma = db.Firmy.Find(id);
            if (firma == null)
            {
                return HttpNotFound();
            }
            return View(firma);
        }

        // POST: /Firmy/Edit/X
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Branza,Nazwa,Opis,NIP, email, miasto, kod_pocztowy, adres, numer_telefonu, ocena, ocena_cz, ocena_j, ocena_ce")] Firma firma)
        {
            if (ModelState.IsValid)
            {
                db.Entry(firma).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(firma);
        }

        // GET: /Firmy/Delete/X
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Firma firma = db.Firmy.Find(id);
            if (firma == null)
            {
                return HttpNotFound();
            }
            return View(firma);
        }

        // POST: /Firmy/Delete/X
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Firma firma = db.Firmy.Find(id);
            db.Firmy.Remove(firma);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

system_oceny/Controllers/OcenaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using system_oceny.Models;

namespace system_oceny.Controllers
{
    public class OcenaController : Controller
    {
        private FirmaDBCtxt db = new FirmaDBCtxt();

        //GET:
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Ocena/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ocenaId, ocenaG, ocena_czas, ocena_jakosc, ocena_cena, login, FirmaId")] Ocena ocena)
        {
            if (ModelState.IsValid)
            {
                db.Oceny.Add(ocena);
                db.SaveChanges();
                ranking(ocena.FirmaId);
                return RedirectToAction("Details", "Firmy", new { id = ocena.FirmaId });
            }
            return View(ocena);
        }

        // GET: /Comment/Edit/X
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ocena ocena = db.Oceny.Find(id);
            if (ocena == null)
            {
                return HttpNotFound();
            }
            return View(ocena);
        }

        // POST: /Comment/Edit/X
        [HttpPost]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ocenaId, ocenaG, ocena_czas, ocena_jakosc, ocena_cena, login, FirmaId")] Ocena ocena)
        {
            // komentarz.data = DateTime.Today;
            if (ModelState.IsValid)
            {
                db.Entry(ocena).State = EntityState.Modified;
                db.SaveChanges();
                ranking(ocena.FirmaId);
                return RedirectToAction("Details", "Firmy", new { id = ocena.FirmaId });
            }
            return View(ocena);
        }

        //Statystyki firmy upgrade
        private void ranking(int id)
        {
            Firma firma = db.Firmy.Find(id);
            db.Entry(firma).State = EntityState.Modified;
            firma.ilosc_ocen = 0;
            firma.ocena = 0;
            firma.ocena_ce = 0;
            firma.ocena_cz = 0;
            firma.ocena_j = 0;
            foreach (Ocena ocena in db.Oceny)
            {
                if (ocena.FirmaId == id)
                {
                    firma.ocena += ocena.ocenaG;
                    firma.ocena_ce += ocena.ocena_cena;
                    firma.ocena_cz += ocena.ocena_czas;
                    firma.ocena_j += ocena.ocena_jakosc;
                    firma.ilosc_ocen++;
                }
            }

            firma.ocena /= firma.ilosc_ocen;
            firma.ocena_ce /= firma.ilosc_ocen;
            firma.ocena_cz /= firma.ilosc_ocen;
            firma.ocena_j /= firma.ilosc_ocen;
            db.SaveChanges();
        }
	}
}

system_oceny/Views/Firmy/Create.cshtml
@model system_oceny.Models.Firma

@{
    ViewBag.Title = "Create";
}

<h2>Stwórz</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Firma</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Branza, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Branza, new SelectList(new[] { "Komputerowa", "Spożywcza", "Handlowa", "Usługowa", "Samochodowa", "Inna" }), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Branza)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa)
                @Html.ValidationMessageFor(model => model.Nazwa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NIP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NIP)
                @Html.ValidationMessageFor(model => model.NIP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis)
                @Html.ValidationMessageFor(model => model.Opis)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email)
                @Html.ValidationMessageFor(model => model.email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numer_telefonu, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numer_telefonu)
                @Html.ValidationMessageFor(model => model.numer_telefonu)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adres, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adres)
                @Html.ValidationMessageFor(model => model.adres)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kod_pocztowy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kod_pocztowy)
                @Html.ValidationMessageFor(model => model.kod_pocztowy)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miasto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miasto)
                @Html.ValidationMessageFor(model => model.miasto)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

system_oceny/Views/Firmy/Delete.cshtml
@model system_oceny.Models.Firma

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy napewno chcesz usunac ta firmę z bazy danych?</h3>
<div>
    <h4>Firma</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Branza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

system_oceny/Views/Firmy/Details.cshtml
@model system_oceny.Models.Firma

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<div class="row">
    <div class="col-md-8">
        <h4>Firma</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nazwa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nazwa)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Branza)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Branza)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Opis)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Opis)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.numer_telefonu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.numer_telefonu)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.adres)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.adres)
            </dd>
            <dd>
                @Html.DisplayFor(model => model.kod_pocztowy) @Html.DisplayFor(model => model.miasto)
            </dd>
        </dl>

        <h4>Galeria</h4> 
            @Html.ActionLink("Przeglądaj galerię", "Index", "Image", new { id = Model.Id }, null)
        
        <h4>Komentarze:</h4>
        <hr />
        @if (!User.Identity.Name.Equals(""))
        {
            @Html.ActionLink("Dodaj komentarz", "Create", "Comment", new { FirmaId = Model.Id, autor = User.Identity.Name }, null)
        }

        <p>
            @foreach (var item in Model.Komentarz)
            {
                <dd>
                    @Html.DisplayFor(modelItem => item.tresc)
                    <br />~@Html.DisplayFor(modelItem => item.autor)
                    <br /><i>@Html.DisplayFor(modelItem => item.data)</i>
                    @if (User.Identity.Name.Equals(item.autor) || User.Identity.Name.Equals("Moderator"))
                    {
                        <br />@Html.ActionLink("edytuj  ", "Edit", "Comment", new { id = item.komentarzID }, null)
                        @Html.ActionLink("skasuj", "Delete", "Comment", new { id = item.komentarzID }, null)
                    }
                    <br /><br />
                </dd>
            }
        </p>

    </div>

    <div class="col-md-4">
        <h4>Ocena użytkowników:</h4>
        <hr />
        <b>Ocena: @Html.DisplayFor(model => model.ocena)</b> 
        <br/>Jakość: @Html.DisplayFor(model => model.ocena_j)
        <br /> Cena: @Html.DisplayFor(model => model.ocena_cz)
        <br />Czas: @Html.DisplayFor(model => model.ocena_ce)
        <br />na podstawie @Html.DisplayFor(model => model.ilosc_ocen) Ocen
        <br />
        
        <br />
        <b>Twoja ocena: </b>
        @if (!User.Identity.Name.Equals(""))
        {
            int existingRate = 0;
            foreach (var item in Model.Oceny)
            {
                if (item.login == User.Identity.Name)
                {
                    <dd>
                        @Html.DisplayFor(modelItem => item.ocenaG)
                    </dd>
                    existingRate = item.ocenaId;
                }
            }
            if (existingRate > 0)
            {
                <dd>
                    @Html.ActionLink("edytuj ocenę", "Edit", "Ocena", new { id = existingRate }, null)
                </dd>
            }
            else if (existingRate == 0 && !User.Identity.Name.Equals(""))
            {
                <dd>
                    <div>Jeszcze nie oceniłeś tej firmy</div>
                    @Html.ActionLink("dodaj ocenę", "Create", "Ocena", new { FirmaId = Model.Id, login = User.Identity.Name }, null)
                </dd>
            }
        }
        else
        {
            <dd>
                @Html.ActionLink("Zaloguj się", "Login", "Account", null, null)
            </dd>
        }
    </div>

</div>



<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Wróć do listy", "Index")
</p>

system_oceny/Views/Firmy/Edit.cshtml
@model system_oceny.Models.Firma

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Firma</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ocena)
        @Html.HiddenFor(model => model.ocena_ce)
        @Html.HiddenFor(model => model.ocena_cz)
        @Html.HiddenFor(model => model.ocena_j)

        <div class="form-group">
            @Html.LabelFor(model => model.Branza, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Branza)
                @Html.ValidationMessageFor(model => model.Branza)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa)
                @Html.ValidationMessageFor(model => model.Nazwa)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NIP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NIP)
                @Html.ValidationMessageFor(model => model.NIP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis)
                @Html.ValidationMessageFor(model => model.Opis)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email)
                @Html.ValidationMessageFor(model => model.email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numer_telefonu, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numer_telefonu)
                @Html.ValidationMessageFor(model => model.numer_telefonu)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adres, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adres)
                @Html.ValidationMessageFor(model => model.adres)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kod_pocztowy, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kod_pocztowy)
                @Html.ValidationMessageFor(model => model.kod_pocztowy)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miasto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miasto)
                @Html.ValidationMessageFor(model => model.miasto)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>